# Exception handling

a = input("Enter the value of a: ") 5
b = input("Enter the value of b: ") y

try:
    print("The sum is: ", int(5) + int(y))
except Exception as e:
    print("Error: ", e)

print("Program continues...")